mqtt:
  host: $MQTT_HOST
  user: $MQTT_USER
  password: $MQTT_PASSWORD

variables:
  doorstatus:
    topic: c3re/hhdst
    cast: bool
  doorstatus_ts:
    topic: c3re/hhdst_tsu
    cast: int
  clubraum_temp:
    topic: c3re/huette/klima/clubraumtemp
    cast: float
  werkstatt_temp:
    topic: c3re/huette/klima/werkstatttemp
    cast: float
  status_msg:
    topic: c3re/hhdst_msg
    cast: string


extra_files:
  prusaxl_online.json:
    topic: c3re/prusa-xl/online
  prusaxl_status.json:
    topic: c3re/prusa-xl/status/printer/state
  prusaxl_percentage.json:
    topic: c3re/prusa-xl/status/job/progress