mqtt:
  host: $MQTT_HOST
  user: $MQTT_USER
  password: $MQTT_PASSWORD

variables:
  doorstatus:
    topic: c3re/hhdst
    cast: bool
  doorstatus_ts:
    topic: c3re/hhdst_tsu
    cast: int
  clubraum_temp:
    topic: c3re/huette/klima/clubraumtemp
    cast: float
  werkstatt_temp:
    topic: c3re/huette/klima/werkstatttemp
    cast: float

extra_files:
  prusaxl_online.json:
    topic: dirk/prusa-xl/online
  prusaxl_status.json:
    topic: dirk/prusa-xl/status
  prusaxl_percentage.json:
    topic: dirk/prusa-xl/percentage